FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages wget
RUN install_packages jq 
RUN install_packages default-jre 

COPY . /

COPY start.sh /usr/src/

RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
